services:
  - type: web
    name: agente-bi-backend
    runtime: python
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: AUTHORIZED_EMAILS
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
