"""Initial baseline

Revision ID: e114418c6081
Revises: 
Create Date: 2026-05-15 14:02:35.327662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e114418c6081'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dashboard_items', type_='foreignkey')
    op.drop_constraint(None, 'dashboard_items', type_='foreignkey')
    op.create_foreign_key(None, 'dashboard_items', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'dashboard_items', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.add_column('simulations', sa.Column('current_round', sa.Integer(), nullable=True))
    op.alter_column('user_configs', 'preferred_provider',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_configs', 'preferred_provider',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('simulations', 'current_round')
    op.drop_constraint(None, 'dashboard_items', type_='foreignkey')
    op.drop_constraint(None, 'dashboard_items', type_='foreignkey')
    op.create_foreign_key(None, 'dashboard_items', 'messages', ['message_id'], ['id'])
    op.create_foreign_key(None, 'dashboard_items', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###
